### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type

### ISSUE THREAD

**Issue by xiongdashan** [lucabriguglia/Kledex#102] opened 2020-01-08 07:20 UTC
.net core 3.1 mvc api

add Kledex in startup.cs
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddKledex(typeof(Program));
            services.AddControllers();
        }
```
exception:
`
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Builder.IApplicationBuilder' while attempting to activate 'Kledex.Extensions.KledexAppBuilder'.`

**Comment by lucabriguglia** [comment] 2020-01-08 07:52
I'll try to reproduce it

**Comment by lucabriguglia** [comment] 2020-01-08 12:09
It works if you change Program.cs from:

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
            });
}
```

to:

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();
}
```

It looks like the `IWebHostBuilder` doesn't register the `IApplicationBuilder`

**Comment by xiongdashan** [comment] 2020-01-09 00:40
Okay.
So this framework can't use in .net framework 4.8?

**Comment by lucabriguglia** [comment] 2020-01-09 11:13
Kledex is based on .NET Standard 2.1 which is not currently supported in .NET Framework 4.8.
Please check the compatibility for .NET Standard here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard.

**Comment by xiongdashan** [comment] 2020-01-10 02:23
How can i use Autofac directly, without ServiceCollection;

Like
```
  var servcies = new ServiceCollection();
            servcies.AddKledex();
```

to

```
  var builder = new ContainerBuilder()
  builder.Register......
```

**Comment by xiongdashan** [comment] 2020-01-10 05:02
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Kledex 2.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

```

**Comment by lucabriguglia** [comment] 2020-01-10 09:23
You should be able to do something like this:

```
servcies.AddKledex();
var builder = new ContainerBuilder();
builder.Populate(services);
// add other stuff to Autofac
```

**Comment by xiongdashan** [comment] 2020-01-10 09:26
Yes, I using builder.Populate...
But my project is Mvc  Web Api using .net framewrok 4.8.

**Comment by lucabriguglia** [comment] 2020-01-10 09:42
As I have already mentioned ..NET Standard 2.1 is not supported yet in .NET Framework 4.8.

**Comment by xiongdashan** [comment] 2020-01-10 09:44
Okay, thanks for your replay。

**Comment by lucabriguglia** [comment] 2020-01-10 15:03
Closing as it is established that it's a compatibility issue.

**Closed by lucabriguglia** 2020-01-10 15:03 UTC

**Comment by Vikaskumargd** [comment] 2020-05-27 16:38
Do we have a permanent fix for this ?
not below one :
```
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();
}
```

**Comment by lucabriguglia** [comment] 2020-05-28 08:07
I don't think so, sorry.
